# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bccac53ec0a7441ad65ea305e26358f4bf51bc8b46ea2189b3cd6652e66518d92d173ad42eb9fa1dbdee5feea39d94a1a2bfd3e575b8ea529b5f41a6272adac

test:
  secret_key_base: 68601f521d7263ec858c1f9dbaa34bfb18e33bc353c528b77d360335b503fa9bb088925164c5a792665c119947f62fe3cd92abd49c17ed01d9250bcd9012a8b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
